### ISSUE TITLE
Select event handler..?

### ISSUE THREAD

**Issue by sarpay** [AndrejGajdos/nested-datatables#1]
This plugin helped me a big deal, thank you for putting it together.. Is there a way to catch the event of a row selection which expands to show the detail table?

**Comment by AndrejGajdos** [comment]
Hi @sarpay glad to hear that this library helped you. Check the last version and README, I added `onShowChildHierarchy` and `onHideChildHierarchy` events

**Comment by sarpay** [comment]
hello.. i tried the new build right after i saw your message. first thing i noticed was that name of the library has changed to nested.tables.min.js. after i replaced the include with the latest build, i started getting the following error : "Uncaught ReferenceError: lib is not defined".. in short it seems that lib is no longer available for initialization.
