### ISSUE TITLE
Cannot initialize plugin

### ISSUE THREAD

**Issue by sarpay** [AndrejGajdos/nested-datatables#2]
hello.. i tried the new build right after i saw your message. first thing i noticed was that name of the library has changed to nested.tables.min.js. after i replaced the include with the latest build, i started getting the following error : "Uncaught ReferenceError: lib is not defined".. in short it seems that lib is no longer available for initialization.

**Comment by AndrejGajdos** [comment]
Hi @sarpay I tried it and it should work. I changed constructor.

Does `nestedTables.TableHierarchy` work for you?

```javascript
var table = new nestedTables.TableHierarchy("example", dataInJson, settings);
table.initializeTableHierarchy();
```
