### ISSUE TITLE
nested.datatables.min.js file not found

### ISSUE THREAD

**Issue by kadamomkar610** [AndrejGajdos/nested-datatables#3]
Hi Andrej,

Please share with me the old nested.datatables.min.js file.

As nested.tables.min.js file does not have run the my code and gives lib is not defined error.

Please reply soon..

Thanks,
Omkar Kadam

**Comment by AndrejGajdos** [comment]
@kadamomkar610 If you try to install previous version from npm 0.0.3? You can also check a [previous commit](url)

**Comment by kadamomkar610** [comment]
Hi @AndrejGajdos 
Actually I had used External JS link mensioned below:
https://rawgit.com/AndrejGajdos/nested-datatables/master/dist/nested.datatables.min.js
But this link is not working. 
So I got the file from your commit.
Thanks for replying and thanks for creating this library.

**Comment by AndrejGajdos** [comment]
@kadamomkar610  Thank you. I updated the [jsfiddle](https://jsfiddle.net/andrej_gajdos/zu11wk2o/37/) in README
