### ISSUE TITLE
nested-datatables / IE11

### ISSUE THREAD

**Issue by serio72** [AndrejGajdos/nested-datatables#5]
Hi Andrej,

I'm using your amazing script and it works like a charm on all browsers, but not in ie11 https://msdn.microsoft.com/query/dev12.query?appId=Dev12IDEF1&l=IT-IT&k=k(VS.WebClient.Help.SCRIPT438) 'from' .

Can you help me? Or it uses features not available in ie?

Thanks
Sergio

**Comment by AndrejGajdos** [comment]
I didn't test it in IE11. Can you post the error or describe the issue?

**Comment by serio72** [comment]
Please open your demo link and you can see what happens. 
It seems that isn't recognized from statement for an object, but I'm js-newbie and I have difficulties to understand exactly what happens.

**Comment by AndrejGajdos** [comment]
I use Mac and don't have any Windows virtual machine. It would be easier for me if you can post the error here.

**Comment by serio72** [comment]
Here what happens.

![image](https://user-images.githubusercontent.com/6168297/38989285-9252e0ae-43d6-11e8-84e0-4addc1d1327f.png)

May this help you on debug? https://www.browserling.com/internet-explorer-testing

Many thanks for your effort!!!!

**Comment by AndrejGajdos** [comment]
Thanks, I will take a look at it.

**Comment by serio72** [comment]
it seems you used some html element/feature that ie11 don't treat. Edge is more compliant ad there works fine

**Comment by AndrejGajdos** [comment]
IE 11 doesn't support [Array.from](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) method. I fixed that by adding Babel Polyfill into the project.
