### ISSUE TITLE
Configuring the nested tables?

### ISSUE THREAD

**Issue by x10** [AndrejGajdos/nested-datatables#6]
Hi there!

I'm glad to find your example!

Curious if you could explain how to nest the tables without the headers and pagination? I'm hoping to achieve something like the attached image with datatables.

Christen

![nested](https://user-images.githubusercontent.com/99417/39775506-51a08c70-52bb-11e8-86a6-1ef4ba7f497a.png)

**Comment by AndrejGajdos** [comment]
This library doesn't support this use-case. This library drills down data for whole row, but you want to drill down for a set of columns. I keep this issue open and if more people ask for this feature, I will consider to implement it. Currently, I don't have a free time for open-source work.

**Comment by x10** [comment]
Thanks for the response @AndrejGajdos If I removed the first 3 columns in the mockup and just drilled down each row would this example work? I'm curious if I can turn off the pagination and other features of the nested tables to achieve a clean look.

**Comment by AndrejGajdos** [comment]
Actually you don't need to remove columns. If you try it out, it will work but it will look a bit different. 
There is a space between an expanded row and child table and columns in child table doesn't depend on parent table or data in expended row. With that being said, columns in child table are not aligned with columns in parent table, but if you change some css you can achieve very similar visualization.

For example row with values "Campaign #23423423 Events and Marketing" and "$40.86" needs to be defined as a child table. The row "Order #3242342", "Order Qty", "$40.86" can be defined as a child table or you can define this row as a header for the child table [Imgur](https://i.imgur.com/aOQv7nh.png).

You can customize [datatable settings](https://datatables.net/reference/option/) (turn off pagination, etc), by `settings` object:

```javascript
var settigns = {
     "iDisplayLength": 20,
     "bLengthChange": false,
     "bFilter": false,
     "bSort": false,
     "bInfo": false
};

var table = new lib.NestedTables("example", dataInJson, settigns);
table.initializeTableHierarchy(); 
```

**Comment by mahjnalisha** [comment]
Hi @AndrejGajdos ,
Feel happy to see this example of nested datatables 
How could I be able to call the server side data without using the json data in the client side?

**Comment by AndrejGajdos** [comment]
@mahjnalisha it is not possible to use this library without data in json format. You need to use ajax to get data from server to client. As soon as you have json data on client, you can edit json object and rename columns.

**Comment by mahjnalisha** [comment]
@AndrejGajdos ,
how could I be able to work on different tables data. I need to add some css class on the nested table thead th section. How could I achieve that and can you show how could I be able to rename the column in the client side if it is nested rows?

**Comment by mahjnalisha** [comment]
@AndrejGajdos ,
How can I be able to the add the buttons in the table

**Comment by AndrejGajdos** [comment]
@mahjnalisha here you can see how to add styles into inner table https://jsfiddle.net/zu11wk2o/256/ and here you can see how to add html elements into table cell https://jsfiddle.net/zu11wk2o/249/
