### ISSUE TITLE
Having multiple nested tables causing error.

### ISSUE THREAD

**Issue by squidwardthetentacles** [AndrejGajdos/nested-datatables#7]
having two different nested tables in one web page, causing error when expanding any row in the first table.

Uncaught TypeError: Cannot read property '0' of undefined
    at mt.fn.init.fnOpen (nested.tables.min.js:formatted:12961)
    at HTMLTableRowElement.<anonymous> (nested.tables.min.js:formatted:10517)
    at HTMLDivElement.dispatch (nested.tables.min.js:formatted:5101)
    at HTMLDivElement.g.handle (nested.tables.min.js:formatted:5033)

**Comment by squidwardthetentacles** [comment]
https://jsfiddle.net/sqiudward/js7eydcf/60/

**Comment by yakupme** [comment]
I have got the same issue. Any solutions for this issue ? Thanks

**Comment by AndrejGajdos** [comment]
I am sorry, but I have a lot of work right now. I will take a look at it during Christmas holidays

**Comment by yakupme** [comment]
Thanks @AndrejGajdos . Your plugin does great job. Thanks for your effort.

**Comment by AndrejGajdos** [comment]
@squidwardthetentacles @yakupme it should be fixed in the latest release.
