### ISSUE TITLE
Adding sorting arrows on the table headers

### ISSUE THREAD

**Issue by yakupme** [AndrejGajdos/nested-datatables#9]
```

                    var getTableHeader = $('.tableWrapper table.dataTable th');
               
                    getTableHeader.append('<span class="arrow-direction descArr"></span>');

                    getTableHeader.click(function(e){
                    	  e.preventDefault();
	                      $(this).find('span').toggleClass('ascArr descArr');
	                      
                    });

```
Thanks once again for your great plugin. I would like to add a sorting arrow on the table headers. When I try with the above code, it just adds on the parent table headers only. Do you have any suggestions ?

**Comment by yakupme** [comment]
@AndrejGajdos Thanks for your quick reply. 
https://jsfiddle.net/yakupme/vfgjy726/

I would like to add a span in the all table th for sorting icon. It's just adding on the top level only.
It does not add on the 2. and 3 level table headers.

**Comment by AndrejGajdos** [comment]
@yakupme sorting in Datatables is disabled by default. You need to change `bSort` parameter to true [jsfiddle](https://jsfiddle.net/ajt3hwro/)

**Comment by yakupme** [comment]
Thanks a lot @AndrejGajdos .
